name: Test
on: [push, pull_request]


env:
  GO_VERSION: 1.16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download && go test -race ./...
      - run: cd _examples && go mod download && go test -race ./...
